services:
  kafka: 
    image: confluentinc/cp-kafka
    ports: 
      - "9092:9092"
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: "192.168.81.97:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.81.97:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
